### PR TITLE
403 errors are now handled by a custom exception

### LINKED ISSUE #23: 403 responses should be handled by an exception
The SDK does not current handle 403 responses from the API. The resulting in output that is difficult t consume.

ex.
image

The SDK should return a custom exception with a friendly error message, similar to way other 4xx errors are handled.

### PR DESCRIPTION
**Pull request by ohryan**
Resolves #23 

## Description

Added a custom `AccessDeniedException`.

## Visuals

N/A

## Testing Instructions

To test attempt to write to an endpoint using a read-only API key.

## Related Documentation

N/A

-

## Pre-review Checklist

- [ ] Acceptance criteria have been satisfied and marked in the related issue.
- [ ] Feature/Unit tests have been added and/or updated (where appropriate).
- [ ] Self-review of code changes has been completed.
- [ ] Self-review of UI and UX changes has been completed, including dark mode and mobile responsiveness.
  - [ ] UI matches the provided Figma mockups (when available).
- [ ] Modified and surrounding functionality has been tested. Considerations have been made for both new and existing servers and sites.

### CODE REVIEW

**Review by danielmlozano — APPROVED** [review]
:100:

File: src/Exceptions/AccessDeniedException.php [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+namespace DeliciousBrains\SpinupWp\Exceptions;
+
+use Exception;
+
+class AccessDeniedException extends Exception
+{
+    public function __construct()
+    {
+        parent::__construct('Your API token does not have permission to that resource.', 401);
```
Comment (A5hleyRich) [inline src/Exceptions/AccessDeniedException.php:11]: @ohryan @danielmlozano should this not be `403`?

Comment (ohryan) [reply src/Exceptions/AccessDeniedException.php]: Right, what the heck! Fixed.
